name: Build Android App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # پکیج libtinfo-dev جایگزین libtinfo5 شده است
          sudo apt-get install -y python3-pip git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo-dev cmake libffi-dev libssl-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build with Buildozer
        run: |
          # مسیرهای پیش‌فرض را به صورت دستی تنظیم می‌کنیم
          export ANDROID_HOME=$HOME/android-sdk
          export ANDROID_NDK_HOME=$HOME/android-ndk
          
          # این دستور باعث می‌شود buildozer به جای تلاش برای دانلود، از محیط استفاده کند
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-debug
          path: bin/*.apk
