name: Build Android App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev

      - name: Install Buildozer
        run: pip install buildozer cython

      - name: Build with Buildozer
        run: |
          # اجبار به استفاده از SDK و NDK نصب شده در سیستم به جای دانلود
          export ANDROID_HOME=/usr/local/lib/android/sdk
          export ANDROID_NDK_HOME=/usr/local/lib/android/sdk/ndk-bundle
          
          # اجرای بیلد
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: app-debug
          path: bin/*.apk
